import Footer from './Components/Footer/Footer'
import Navbar from './Components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="cupcake">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
